apiVersion: v1
kind: Namespace
metadata:
  name: cp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: cp2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: cp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
        - name: redis
          image: pablocondecp2zbo9ruacr.azurecr.io/aks/redis:casopractico2
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis_password
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: cp2
spec:
  selector:
    app: azure-vote-back
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: cp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
        - name: azure-vote-front
          image: pablocondecp2zbo9ruacr.azurecr.io/aks/azure-vote-front:casopractico2
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: azure-vote-back
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis_password
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: cp2
spec:
  selector:
    app: azure-vote-front
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer