# --------------------
# SSH keypair for VM (generated by Terraform)
# NOTE:
# - The private key will be stored in the Terraform state (as part of tls_private_key resource).
# - We DO NOT output the private key; we only write it to a local file in ../.keys (ignored by Git).
# --------------------
resource "tls_private_key" "vm_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_file" "vm_ssh_private" {
  filename             = "${var.ssh_key_output_dir}/${var.ssh_key_name}"
  content              = tls_private_key.vm_ssh.private_key_pem
  file_permission      = "0600"
  directory_permission = "0700"
}

resource "local_file" "vm_ssh_public" {
  filename             = "${var.ssh_key_output_dir}/${var.ssh_key_name}.pub"
  content              = tls_private_key.vm_ssh.public_key_openssh
  file_permission      = "0644"
  directory_permission = "0700"
}