variable "project" {
  type        = string
  description = "Project identifier (e.g., casopractico2)"
}

variable "env" {
  type        = string
  description = "Environment (e.g., dev)"
}

variable "location" {
  type        = string
  description = "Azure region (e.g., italynorth)"
}

variable "name_prefix" {
  type        = string
  description = "Unique prefix for globally-unique names (ACR) and resource naming"
}

variable "vm_admin_username" {
  type        = string
  description = "Admin username for the Linux VM"
  default     = "azureuser"
}

# --------------------
# SSH key (generated by Terraform)
# --------------------
variable "ssh_key_output_dir" {
  type        = string
  description = "Directory (relative to terraform/ folder) where the generated SSH key pair will be written"
  default     = "../.keys"
}

variable "ssh_key_name" {
  type        = string
  description = "Base filename for the generated SSH key (private key). Public key will be <name>.pub"
  default     = "vm_ubuntu_key"
}

variable "aks_node_count" {
  type        = number
  description = "Number of nodes in the AKS node pool"
  default     = 1
}

variable "aks_vm_size" {
  type        = string
  description = "VM size for AKS nodes"
  default     = "Standard_B2s_v2"
}

variable "aks_dns_prefix" {
  type        = string
  description = "DNS prefix for AKS"
  default     = "cp2aks"
}