---
- name: Asegurar que el espacio de nombres de AKS existe
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ aks_namespace }}"

- name: Aplicar el secreto de Redis en AKS
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', playbook_dir ~ '/../../templates/redis-secret.yaml.j2') | from_yaml }}"